---
# cca.setup.cca-manager

# Unique SSH key file that must match and work against the Splunk infrastructure
# servers. Update the name if needed.
cca_ansible_private_key_file: '~/secrets/cca_ansible_id_rsa'

# Specific settings for current cca_for_splunk release.
cca_for_splunk_repo_url: 'https://github.com/innovationfleet/cca_for_splunk'
cca_for_splunk_directory: 'cca_for_splunk'
cca_manager_cca_for_splunk_path: '{{ cca_manager_user_dir }}/master/{{ cca_for_splunk_directory }}'
cca_python_minor_version: '3.9'
cca_python_release: '3.9.10'
cca_ansible_minor_version: '2.12'
cca_ansible_release: '2.12.5'
cca_manager_user_dir: '{{ ansible_facts.user_dir }}'
cca_manager_directories:
  - "{{ cca_manager_user_dir }}/secrets"
  - "{{ cca_manager_user_dir }}/master"
  - "{{ cca_manager_user_dir }}/tools/python-venv"
  - "{{ cca_manager_user_dir }}/tools/mitogen"
cca_manager_ansible_vault_secret_path: '~/secrets/cca_ansible_vault_secret'
cca_ansible_roles_path: './roles:~/master/cca_for_splunk/roles'

# CCA for Splunk is a strong supporter of the Mitogen framework as it speeds up
# CCA playbooks by at least 4X. Read more details about it below.
# https://mitogen.networkgenomics.com/ansible_detailed.html
# https://github.com/mitogen-hq/mitogen/tags
cca_install_mitogen: true
cca_use_mitogen_strategy: true
cca_manager_mitogen_repo_url: 'https://github.com/mitogen-hq/mitogen.git'
cca_manager_mitogen_path: '{{ cca_manager_user_dir }}/tools/mitogen'
cca_manager_mitogen_release: 'v0.3.3'

