---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.1
- name: Configure user profile
  ansible.builtin.template:
    src: user_profile/dot.profile.j2
    dest: '{{ splunk_path }}/.profile'
    mode: '0700'
    owner: '{{ splunk_user }}'
    group: '{{ splunk_user_group_name }}'
