
---
# tasks file for cca.common.setup-wizard
#
# Description:
#
# Prerequisite:
#
# Author: André Enemark
#         Roger Lindquist
#
# Release: v2022.3.2

- name: Set base path for repo
  ansible.builtin.set_fact:
    repo_base_path: "{{ cca_environment.default_repo_base_path }}"

- name: Prompt for a directory name where to store Splunk CCA Infrastructure config, default {{ cca_environment.default_infra_repo_name }}
  ansible.builtin.pause:
    prompt: "Enter directory name in which to save the infra config ({{ cca_environment.default_infra_repo_name }})"
  register: wizard_infra_repo_name

- name: Set infra repo path
  ansible.builtin.set_fact:
    infra_repo_path: "{{ cca_infra_repo_base_path + '/' + cca_environment.default_infra_repo_name if wizard_infra_repo_name.user_input | length == 0 else cca_infra_repo_base_path + '/' + wizard_infra_repo_name.user_input }}"

- ansible.builtin.set_fact:
    absolute_infra_repo_path: "{{ infra_repo_path }}"

- name: Prompt for a directory name where to store Splunk CCA Onboarding config, default {{ cca_environment.default_onboarding_repo_name }}
  ansible.builtin.pause:
    prompt: "Enter directory name in which to save the onboarding config ({{ cca_environment.default_onboarding_repo_name }})"
  register: wizard_onboarding_repo_name

- name: Set onboarding repo path
  ansible.builtin.set_fact:
    onboarding_repo_path: "{{ cca_onboarding_repo_base_path + '/' + cca_environment.default_onboarding_repo_name if wizard_onboarding_repo_name.user_input | length == 0 else cca_onboarding_repo_base_path + '/' + wizard_onboarding_repo_name.user_input }}"

- name: Check uniqueness of infra and onboarding directory
  ansible.builtin.assert:
    that:
      - infra_repo_path != onboarding_repo_path
    fail_msg:
      Error, the directory name of both infra and onboarding are the same,
      please change one of these directories name.

- name: Prompt for environment name where to store initial templates
  ansible.builtin.pause:
    prompt: "Enter a environment name without space characters ({{ cca_environment.default_environment_dir }})"
  register: wizard_environment

- ansible.builtin.set_fact:
    environment_dir: "{{ cca_environment.default_environment_dir if wizard_environment.user_input | length == 0 else wizard_environment.user_input }}"

- name: Check if the environments path already exists
  ansible.builtin.stat:
    path: "{{ infra_repo_path }}/environments/{{ environment_dir }}/group_vars/all/cca_splunk_secrets"
  register: stat_cca_splunk_secrets

- name: Get vars from cca_splunk_secrets if it exists
  include_vars:
    file: "{{ infra_repo_path }}/environments/{{ environment_dir }}/group_vars/all/cca_splunk_secrets"
  when:
    - stat_cca_splunk_secrets.stat.exists

- name: Accept random splunk secret or provide your own
  ansible.builtin.pause:
    prompt: "Press enter for a random secret or enter an existing one that is exactly 254 character, ({{ cca_environment.random_splunk_secret }})"
  register: wizard_splunk_secret

- name: Assert length of Splunk secret
  ansible.builtin.assert:
    that:
      - wizard_splunk_secret.user_input | length == 254
    fail_msg: The provided splunk secret is not 254 characters, got ({{ wizard_splunk_secret.user_input | length }})
  when:
    - wizard_splunk_secret.user_input != ''

- ansible.builtin.set_fact:
    splunk_secret: "{{ cca_environment.random_splunk_secret if wizard_splunk_secret.user_input | length == 0 else wizard_splunk_secret.user_input }}"
