---
# tasks file for cca.common.setup-wizard
#
# Description:
#
# Prerequisite:
#
# Author: André Enemark
#
# Release: 2022.2.4

 - name: Create directory if it don't exist
   ansible.builtin.file:
     path: "{{ item }}"
     state: directory
   loop:
     - "{{ cca_environment.infrastructure_repo_dir }}"
     - "{{ cca_environment.onboarding_repo_dir }}"

 - name: Copy template files for infrastructure - may take some time
   ansible.builtin.copy:
     src: "{{ script_cwd }}/templates/infrastructure_template/"
     dest: "{{ cca_environment.infrastructure_repo_dir }}"

 - name: Copy template files for onboarding - may take some time
   ansible.builtin.copy:
     src: "{{ script_cwd }}/templates/onboarding_template/"
     dest: "{{ cca_environment.onboarding_repo_dir }}"

 - name: Move ENVIRONMENT_NAME to new env directory for infra - may take some time
   ansible.builtin.copy:
     src: "{{ cca_environment.infrastructure_repo_dir }}/{{ item }}/ENVIRONMENT_NAME/"
     dest: "{{ cca_environment.infrastructure_repo_dir }}/{{ item }}/{{ environment_dir }}"
   loop:
     - "environments"

 - name: Cleanup unused ENVIRONMENT_NAME directory for infra - may take some time
   ansible.builtin.file:
     path: "{{ cca_environment.infrastructure_repo_dir }}/{{ item }}/ENVIRONMENT_NAME"
     state: 'absent'
   loop:
      - "environments"

 - name: Move ENVIRONMENT_NAME to new env directory for onboarding - may take some time
   ansible.builtin.copy:
     src: "{{ cca_environment.onboarding_repo_dir }}/{{ item }}/ENVIRONMENT_NAME/"
     dest: "{{ cca_environment.onboarding_repo_dir }}/{{ item }}/{{ environment_dir }}"
   loop:
     - "environments"
     - "splunk/etc/deployment-apps"
     - "splunk/etc/shcluster"
     - "splunk/etc/master-apps"
     - "splunk/etc/manager-apps"

 - name: Cleanup unused ENVIRONMENT_NAME directory for onboarding - may take some time
   ansible.builtin.file:
     path: "{{ cca_environment.onboarding_repo_dir }}/{{ item }}/ENVIRONMENT_NAME"
     state: 'absent'
   loop:
     - "environments"
     - "splunk/etc/deployment-apps"
     - "splunk/etc/shcluster"
     - "splunk/etc/master-apps"
     - "splunk/etc/manager-apps"

 - name: Set execute bit on cca_ctrl file
   ansible.builtin.file:
     path: "{{ item }}/cca_ctrl"
     mode: '0700'
   loop:
     - "{{ cca_environment.onboarding_repo_dir }}"
     - "{{ cca_environment.infrastructure_repo_dir }}"
