---
# tasks file for cca.common.setup-wizard
#
# Description:
#
# Prerequisite:
#
# Author: André Enemark
#
# Release: 2022.2.1

- name: Get stat from splunk.secret file
  ansible.builtin.stat:
    path: "{{ splunk_path }}/etc/auth/splunk.secret"
    checksum_algorithm: "sha256"
  register: stat_splunk_secret

- name: Get the current installed secret
  ansible.builtin.shell: "cat {{ splunk_path }}/etc/auth/splunk.secret"
  register: cat_splunk_secret
  when:
    - stat_splunk_secret.stat.exists
