---
# tasks file for cca.splunk.ssl-certificates
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.1.1

- name: Include task to validate certificate depending on cca_splunk_cert_enrollment_method mode
  ansible.builtin.include_tasks: validate_manual_certificates.yml
  when:
    - cca_splunk_cert_enrollment_method == 'manual'
