---
# tasks file for cca.splunk.ssl-certificates
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.1.1
- name: Set fact for web cert to be used in common tasks
  ansible.builtin.set_fact:
    cert_file_name: '{{ cca_splunk_certs_web_cert }}'
    cert_staging_file_name: '{{ cca_splunk_certs_web_staging_cert }}'
    privkey_file_name: '{{ cca_splunk_certs_web_key }}'
    privkey_staging_file_name: '{{ cca_splunk_certs_web_staging_key }}'
    privkey_password: '{{ cca_splunk_certs_web_sslpassword }}'
    encrypt_private_key: '{{ openssl_certs_web_encryption }}'
    facts_variable: 'cca_splunk_web_ssl'
    cert_type: 'web'
  no_log: "{{ hide_password }}"

- name: Validate manual certs to find if they need updates
  include_tasks: validate_manual_certificates.yml
  when:
    - cca_splunk_cert_enrollment_method == 'manual'

- name: Include task to deploy manual certs
  include_tasks: deploy_manual_certs.yml
  when:
    - cca_splunk_cert_enrollment_method == 'manual'
    - final_cert_file_result.changed

