---
# tasks file for cca.splunk.ssl-certificates
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.1
- name: Set fact for web cert to be used in common tasks
  ansible.builtin.set_fact:
    cert_file_name: '{{ cca_splunk_certs_web_cert }}'
    cert_staging_file_name: '{{ cca_splunk_certs_web_staging_cert }}'
    privkey_file_name: '{{ cca_splunk_certs_web_key }}'
    privkey_staging_file_name: '{{ cca_splunk_certs_web_staging_key }}'
    privkey_password: '{{ cca_splunk_certs_web_sslpassword }}'
    encrypt_private_key: '{{ openssl_certs_web_encryption }}'
  no_log: "{{ hide_password }}"

- name: Validate certs
  include_tasks: validate_certificates.yml

# TODO Better logic for when to renew certs.
- name: Include task to deploy manual certs
  include_tasks: deploy_manual_certs.yml
  when:
    ( cca_splunk_cert_enrollment_method == 'manual' and
    stat_web_cert_file.stat.exists | default(false) == false )
    or
    ( renew_web_cert | default(false) == true )

- name: Validate certs
  include_tasks: validate_certificates.yml
