---
# tasks file for cca.core.splunk
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.1

- name: Upgrade precheck, validate that all statuses are as expected
  ansible.builtin.assert:
    that:
      - shcluster_dynamic_captain_flag | default(false)
      - shcluster_initialized_flag | default(false)
      - not shcluster_rolling_restart_flag | default(true)
      - not shcluster_rolling_upgrade_flag | default(true)
      - shcluster_service_ready_flag | default(false)
      - shcluster_stable_captain_flag | default(false)
      - not shcluster_manual_detention_flag | default(true)
      - shcluster_kvstore_status_flag | default(false)
    fail_msg: >-
      Upgrade precheck failed, to override upgrade precheck. Add --extra-vars='{"shcluster_precheck":false}'
    success_msg: >-
      All prechecks passed
  when:
    - shcluster_precheck | default(true)
  check_mode: false

- name: Verify that all SHC members has the same version
  ansible.builtin.assert:
    that:
      - shcluster_splunk_version.stdout.split() | length == 1
    fail_msg: >
      Review SHC status, {{ shcluster_splunk_version.stdout }} versions detected.
  when:
    - shcluster_precheck | default(true)
  check_mode: false
