---
# tasks file for cca.core.splunk
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.1
- name: Check if a splunkd restart is pending
  ansible.builtin.stat:
    path: "{{ splunkd_restart_pending }}"
  register: stat_splunkd_restart_pending

- name: Check if a rolling restart is pending
  ansible.builtin.stat:
    path: "{{ rolling_restart_pending }}"
  register: stat_rolling_restart_pending
  when:
    - inventory_hostname in groups.cluster_managers or
      inventory_hostname in groups.searchhead_members

- name: Check if a cluster bundle push is pending
  ansible.builtin.stat:
    path: "{{ cluster_bundle_push_pending }}"
  register: stat_cluster_bundle_push_pending
  when:
    - inventory_hostname in groups.cluster_managers

- name: Check if a shcluster bundle push is pending
  ansible.builtin.stat:
    path: "{{ shcluster_bundle_push_pending }}"
  register: stat_shcluster_bundle_push_pending
  when:
    - inventory_hostname in groups.searchhead_deployers

- name: Check if a deployment server reload is pending
  ansible.builtin.stat:
    path: "{{ deployment_server_reload_pending }}"
  register: stat_deployment_server_reload_pending
  when:
    - inventory_hostname in groups.deployment_servers
