---
# tasks file for cca.core.splunk
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.4
- name: Perform an orchestrated rolling restart of cluster peers
  block:
    - name: Include tasks to login to splunk cli
      ansible.builtin.include_tasks: splunk_login.yml

    - name: Perform a rolling restart of cluster peers
      shell: "{{ splunk_path }}/bin/splunk rolling-restart cluster-peers -searchable {{ searchable_rolling_restart | default('false') }} --answer-yes"
      register: cluster_peers_rolling_restart_status

    - name: Cleanup state file for rolling restart
      ansible.builtin.file:
        path: "{{ rolling_restart_pending }}"
        state: absent

    - name: Wait for the cluster manager to update its status
      pause:
        minutes: "{{ wait_time_cluster_peers_report | default(3) }}"
        prompt: >-
          Wait {{ wait_time_cluster_peers_report | default(3) }} minutes for the cluster manager to update its status.

    - name: Include tasks check Pre-flight status
      ansible.builtin.include_tasks: check_preflight_status.yml
      vars:
        preflight_command_retries: "{{ cluster_peer_rolling_restart_preflight_retries | default(180) }}"
