---
# tasks file for cca.core.splunk
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.3

- name: Check if splunk is running by examine pid file
  ansible.builtin.stat:
    path: "{{ splunk_path }}/var/run/splunk/splunkd.pid"
  register: stat_splunk_pid

- name: Check current installed splunk version
  ansible.builtin.shell:
    cmd: "timeout 10 {{ splunk_path }}/bin/splunk version --accept-license --answer-yes --no-prompt | awk '{ print $2 }'"
  register: splunk_enterprise_version_result
  when:
    - stat_splunk_pid.stat.exists
  changed_when: false
  check_mode: false

- name: Set fact for current Splunk version or target splunk version of splunk is not running
  ansible.builtin.set_fact:
    current_splunk_enterprise_version: "{{ splunk_enterprise_version_result.stdout | default(splunk_enterprise_version) }}"
