---
# tasks file for cca.core.splunk
#
# Description:
#   The data-model handles everything that comes around settings parameters for
#   Splunk instances based on their role. A Splunk role is mapped to an inventory
#   group in Ansible.
#   Functions for creating, updating and deleting sections, options and values
#   in ini_file is implemented. Splunk .conf files is perfect for the ini_file
#   module as it can configure settings with the concept of atomic precision.
#
# Prerequisite:
#
# Roger Lindquist (github.com/rlinq)
#
# Release: 2022.3.1
- name: Include task for checking cca_for_splunk init state
  include_tasks: check_init.yml

- name: Include task for checking splunk.secret
  include_tasks: check_splunk_secret.yml

- name: Include task ensuring local admin user
  include_tasks: local_users.yml

- name: Include task for checking certificate status
  include_tasks: ../../cca.splunk.ssl-certificates/tasks/validate_certificates.yml

- name: Include task to calculate splunk enterprise version
  include_tasks: get_splunk_version.yml

- name: Run a precheck of the config to find errors
  include_tasks: precheck_settings.yml

- name: Include task for splunk general settings
  include_tasks: set_splunk_general_settings.yml
  when:
    - splunk_conf_general_settings is defined

- name: Include task for splunk group settings
  include_tasks: set_splunk_group_settings.yml
  when:
    - splunk_conf_group_settings is defined

- name: Include task for splunk host settings
  include_tasks: set_splunk_host_settings.yml
  when:
    - splunk_conf_host_settings is defined

- name: Include task for adding Splunk license
  include_tasks: add_license.yml
  when:
    - is_license_manager | default(false)

- name: Include licensed CCA infrastructure tasks
  ansible.builtin.include_role:
    name: "{{ cca_control_infrastructure.role }}"
    tasks_from:
      "{{ cca_control_infrastructure.task }}"
  loop_control:
    loop_var: cca_control_infrastructure
  loop: '{{ cca_control_infrastructure_tasks | default([]) if cca_control_infrastructure_tasks | default([]) is iterable else [] }}'

- name: Restart Splunkd if splunk.secret is replaced
  ansible.builtin.command:
    cmd: "timeout 120 {{ restart_command }}"
  register: splunk_status_result
  until: splunk_status_result.rc == 0
  retries: 5
  delay: 10
  when:
    - result_splunk_secret_replace.changed == true

- name: Check for first time run
  ansible.builtin.stat:
    path: "{{ splunk_path }}/var/run/splunk"
  register: stat_var_run_splunk

- name: Ensure splunk is running on non searchhead members
  ansible.builtin.command:
    cmd: "timeout 120 {{ start_command }}"
  register: splunk_status_result
  until: splunk_status_result.rc == 0
  retries: 5
  delay: 10
  changed_when: "'This appears to be your first time running this version of Splunk.' in splunk_status_result.stdout"
  when:
    - not inventory_hostname in groups.searchhead_members

- name: Wait for a rolling restart on search head cluster to complete
  ansible.builtin.import_tasks: ../../cca.splunk.role-searchhead/tasks/wait_for_shcluster.yml
  when:
    - inventory_hostname in groups.searchhead_members
    - stat_var_run_splunk.stat.exists

- name: Ensure splunk is running on searchhead members
  ansible.builtin.command:
    cmd: "timeout 240 {{ start_command }}"
  register: splunk_status_result
  until: splunk_status_result.rc == 0
  retries: 5
  delay: 10
  changed_when: "'This appears to be your first time running this version of Splunk.' in splunk_status_result.stdout"
  when:
    - inventory_hostname in groups.searchhead_members
