---
# tasks file for cca.core.splunk
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.1
- name: Perform a splunkd restart in a block
  block:
    - name: Restart splunkd on cli
      ansible.builtin.shell: "{{ restart_command }}"
      register: splunk_restart_result
      when:
        ( stat_ansible_managed.stat.exists is defined and
          stat_ansible_managed.stat.exists == true )
        or
        ( cca_splunk_init | default (false) == true )

    - name: Perform a cleanup of state file
      ansible.builtin.file:
        path: "{{ splunkd_restart_pending }}"
        state: absent
      when:
        - splunk_restart_result.changed | default(false) == true
