---
# tasks file for cca.core.splunk
#
# Description: This tasks reads the splunk_conf_general_settings and
#              apply them on each splunk host that is targeted by the
#              playbook.
#
# Prerequisite:
#              splunk_conf_general_settings needs to be defined, if
#              not the task is not included.
#
# Roger Lindquist (github.com/rlinq)
# META_DATE
# META_VERSION

- name: Find Splunk files in etc/system/local
  ansible.builtin.find:
    paths: "{{ splunk_path }}/etc/system/local"
    patterns: "*.conf"
  register: find_splunk_local_conf
  when:
    - accept_cca_management | default(false)
    - not cca_ansible_managed | default(false)

- name: Create a copy of each file in etc/system/local
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ item.path }}.bak-{{ ansible_date_time.iso8601 }}"
    remote_src: true
    mode: '0644'
  loop: "{{ find_splunk_local_conf.files }}"
  when:
    - accept_cca_management | default(false)
    - not cca_ansible_managed | default(false)

- name: Manage header line in splunk files, managed by ansible
  ansible.builtin.ini_file:
    path: "{{ item.filepath }}/{{ item.filename }}"
    section:
    option: '{{ file_managed_by_ansible }}'
    value: null
    state: present
    allow_no_value: true
  loop:
    "{{ splunk_conf_general_settings }}"
  changed_when: false
  no_log: '{{ hide_password }}'

- name: Updates Splunk conf based on general settings
  ansible.builtin.ini_file:
    path: "{{ item.0.filepath }}/{{ item.0.filename}}"
    section: "{{ item.0.section }}"
    option: "{{ item.1.option | default(null)
             if
               item.1.state | default('present') != 'AbsentSection'
             else
               ''
            }}"
    value: "{{ item.1.value | default(null)
             if
               item.1.state | default('present') != 'AbsentSection'
             else
               ''
            }}"
    state: "{{ 'present'
             if
               item.1.state | default('present') == 'present'
             else
               'absent'
            }}"
    allow_no_value: "{{ 'yes' if ( not item.1.value ) else 'no' }}"
    mode: '0644'
  with_subelements:
    - "{{ general_sections_loop }}"
    - options
  register: cca_splunk_settings_update

- name: Include task to notify restart or need to push general settings
  include_tasks: notify_splunk.yml
  when:
    - cca_splunk_settings_update is defined
    - cca_splunk_settings_update.results is defined
