---
# tasks file for cca.core.splunk
#
# Description: This tasks reads the splunk_conf_host_settings and
#              apply them on each splunk host that is targeted by the
#              playbook.
#
# Prerequisite:
#              splunk_conf_host_settings needs to be defined
#
# Roger Lindquist (github.com/rlinq)
# META_DATE
# META_VERSION

- name: Manage header line in splunk files, managed by ansible
  ansible.builtin.ini_file:
    path: "{{ item.filepath }}/{{ item.filename }}"
    section:
    option: '{{ file_managed_by_ansible }}'
    value: null
    state: present
    allow_no_value: true
    mode: '0644'
  loop:
    "{{ splunk_conf_host_settings }}"
  changed_when: false
  no_log: '{{ hide_password }}'

- name: Updates Splunk conf based on host settings
  ansible.builtin.ini_file:
    path: "{{ item.0.filepath }}/{{ item.0.filename}}"
    section: "{{ item.0.section }}"
    option: "{{ item.1.option | default(null)
             if
               item.1.state | default('present') != 'AbsentSection'
             else
               ''
            }}"
    value: "{{ item.1.value | default(null)
             if
               item.1.state | default('present') != 'AbsentSection'
             else
               ''
            }}"
    state: "{{ 'present'
             if
               item.1.state | default('present') == 'present'
             else
               'absent'
            }}"
    allow_no_value: "{{ 'yes' if ( not item.1.value ) else 'no' }}"
    mode: '0644'
  with_subelements:
    - "{{ host_sections_loop }}"
    - options
  register: cca_splunk_settings_update

- name: Include task to notify restart or need to push host settings
  include_tasks: notify_splunk.yml
  when:
    - cca_splunk_settings_update is defined
    - cca_splunk_settings_update.results is defined
