---
# tasks file for cca.core.splunk
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.1
- name: Perform a splunkd restart in a block
  block:
    - name: Include tasks to login to splunk cli
      ansible.builtin.include_tasks:
        splunk_login.yml

# TODO: Check if there is a pending rolling restart before starting
#       a new one, espcially when init the SHC
    - name: Kick off a rolling restart of a SHC member
      ansible.builtin.shell: "{{ shcluster_members_rolling_restart_command }}"
      register: splunk_rolling_restart_result
      when:
        ( stat_ansible_managed.stat.exists is defined and
          stat_ansible_managed.stat.exists == true )
        or
        ( cca_splunk_init | default (false) == true )
      failed_when:
        - splunk_rolling_restart_result.rc != 22
        - splunk_rolling_restart_result.rc != 0

    - name: Perform a cleanup of state file
      ansible.builtin.file:
        path: "{{ rolling_restart_pending }}"
        state: absent
      when:
        - splunk_rolling_restart_result.changed | default(false) == true
