---
# tasks file for cca.core.control
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.3.1

- name: Include licensed CCA post deployment tasks
  ansible.builtin.include_role:
    name: "{{ cca_control_post_deployment.role }}"
    tasks_from:
      "{{ cca_control_post_deployment.task }}"
  loop_control:
    loop_var: cca_control_post_deployment
  loop: '{{ cca_control_post_deployment_tasks | default([]) if cca_control_post_deployment_tasks | default([]) is iterable else [] }}'
