---
# tasks file for cca.core.control
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.1.1

- name: Include licensed CCA post upgrade tasks
  ansible.builtin.include_role:
    name: "{{ cca_control_post_upgrade.role }}"
    tasks_from:
      "{{ cca_control_post_upgrade.task }}"
  loop_control:
    loop_var: cca_control_post_upgrade
  loop: '{{ cca_control_post_upgrade_tasks | default([]) if cca_control_post_upgrade_tasks | default([]) is iterable else [] }}'
