---
# tasks file for cca.core.control
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.1.1

- name: Get cluster manager status
  ansible.builtin.include_tasks: index_clusters/cluster_manager_status.yml
  when:
    - inventory_hostname in groups.cluster_managers

- name: Migrate master-apps on Cluster Manager
  ansible.builtin.include_tasks: index_clusters/cluster_manager_cluster_bundle_dir.yml
  when:
    - inventory_hostname in groups.cluster_managers
    - splunk_enterprise_installed
    - current_splunk_enterprise_version | default(splunk_enterprise_version) | default(splunk_enterprise_version) is version('9.0.0', '>=')
    - not master_apps_migration_completed

- name: Include licensed CCA pre tasks
  ansible.builtin.include_role:
    name: "{{ cca_control_pre.role }}"
    tasks_from:
      "{{ cca_control_pre.task }}"
  loop_control:
    loop_var: cca_control_pre
  loop: '{{ cca_control_pre_tasks | default([]) if cca_control_pre_tasks | default([]) is iterable else [] }}'
