# MENU_DESC=CCA Infrastructure and Onboarding Repo Setup Wizard
# REPO_TYPE=main
# EXTRA_VARS=
- name: Wizard - Setup and aid user to copy and create necessary directories
  hosts: localhost
  connection: local
# TODO: Add function to add secrets using the same secret
# TODO: Prompt for reusing, recreating or adding a new vault secret.

  vars:
    user_home: "{{ ansible_env.HOME }}"
    script_cwd: "{{ ansible_env.PWD | replace('/playbooks','') }}"
    pwd_array: "{{ script_cwd.split('/') }}"
    cca_repo_base: "{{ pwd_array[:-1] | join('/') }}"
    splunk_enterprise_version: "9.0.4"

    cca_environment:
      infrastructure_repo_dir: '{{ user_home }}/data/main/cca_splunk_infrastructure'
      onboarding_repo_dir: '{{ user_home }}/data/main/cca_splunk_onboarding'
      repo_base_path: "{{ cca_repo_base }}"
      cca_repo_path: "{{ user_home }}/clones/cca_for_splunk"
      default_environment_dir: 'cca_lab'
      random_splunk_secret: "{{ lookup('community.general.random_string', base64=True, length=254) }}"
      cca_splunk_secrets:
        - cca_splunk_server_general: "pass4SymmKey"
        - cca_splunk_certs_server: "sslpassword"
        - cca_splunk_certs_server_default: "sslpassword"
        - cca_splunk_certs_inputs: "sslpassword"
        - cca_splunk_certs_outputs: "sslpassword"
        - cca_splunk_certs_web: "sslpassword"
        - cca_splunk_cluster_c1: "pass4SymmKey"
        - cca_splunk_shcluster_c1: "pass4SymmKey"
      cca_splunk_secrets_no_prompt:
        - cca_splunk_cluster_c2: "pass4SymmKey"
        - cca_splunk_cluster_c3: "pass4SymmKey"
        - cca_splunk_cluster_c4: "pass4SymmKey"
        - cca_splunk_cluster_c5: "pass4SymmKey"
        - cca_splunk_cluster_c6: "pass4SymmKey"
        - cca_splunk_cluster_c7: "pass4SymmKey"
        - cca_splunk_cluster_c8: "pass4SymmKey"
        - cca_splunk_cluster_c9: "pass4SymmKey"
        - cca_splunk_shcluster_c2: "pass4SymmKey"
        - cca_splunk_shcluster_c3: "pass4SymmKey"
        - cca_splunk_shcluster_c4: "pass4SymmKey"
        - cca_splunk_shcluster_c5: "pass4SymmKey"
        - cca_splunk_shcluster_c6: "pass4SymmKey"
        - cca_splunk_shcluster_c7: "pass4SymmKey"
        - cca_splunk_shcluster_c8: "pass4SymmKey"
        - cca_splunk_shcluster_c9: "pass4SymmKey"

  pre_tasks:

    - name: Run setup
      ansible.builtin.setup:

    - name: Set sed command for linux/OSx
      ansible.builtin.set_fact:
        sed_cmd: "{% if ansible_os_family == 'Darwin' %}gsed{% else %}sed{% endif %}"

    - name: Prompt for initial names
      ansible.builtin.include_role:
        name: cca.common.setup-wizard
        tasks_from:
          collect_values.yml

    - name: Setup directories and copy template files
      ansible.builtin.include_role:
        name: cca.common.setup-wizard
        tasks_from:
          setup_directories.yml
      when:
        - copy_cca_template_files.user_input | default('yes') == 'yes'

  tasks:
    - name: Wizard init
      ansible.builtin.include_role:
        name: cca.common.setup-wizard
        tasks_from: wizard_init.yml

    - name: Set fact that the current splunk secret is the secret found in cca_splunk_secret_file
      ansible.builtin.set_fact:
        cca_identical: "{{ true if splunk_secret == vars_current_wizard.cca_splunk_secret | default('') }}"

    - name: Instantiate cli user, password and password hash
      ansible.builtin.include_role:
        name: cca.common.setup-wizard
        tasks_from: create_user_seed.yml

    - name: Instantiate general pass4SymmKeys and ssl passwords
      ansible.builtin.include_role:
        name: cca.common.setup-wizard
        tasks_from: generate_secrets.yml
      loop_control:
        loop_var: secret_type
      with_items:
        - "{{ cca_environment.cca_splunk_secrets }}"

    - name: Instantiate cluster specific pass4SymmKeys
      ansible.builtin.include_role:
        name: cca.common.setup-wizard
        tasks_from: generate_secrets_no_prompt.yml
      loop_control:
        loop_var: secret_type
      with_items:
        - "{{ cca_environment.cca_splunk_secrets_no_prompt }}"
